"""added academic_year_id to exam_subjects

Revision ID: d03d38b13889
Revises: 
Create Date: 2026-04-09 19:10:33.744071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd03d38b13889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    with op.batch_alter_table('exam_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('uq_exam_subject_branch'))
        batch_op.create_unique_constraint('uq_exam_subject_year_branch', ['exam_id', 'subject_id', 'academic_year_id', 'branch_id'])
        batch_op.create_foreign_key(None, 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_parent_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teacher_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('interface_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'Unknown'"))
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', mysql.VARCHAR(length=45), server_default=sa.text("''"), nullable=True))
        batch_op.alter_column('interface_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("'Unknown'"))
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_user'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_user'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_parent_user'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exam_subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_exam_subject_year_branch', type_='unique')
        batch_op.create_index(batch_op.f('uq_exam_subject_branch'), ['exam_id', 'subject_id', 'branch_id'], unique=True)
        batch_op.drop_column('academic_year_id')

    op.create_table('parent',
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('photo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('roll_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.ENUM('male', 'female', 'other'), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('occupation', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('emergency_contact', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('national_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('relationship', mysql.ENUM('father', 'mother', 'guardian', 'other'), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'inactive', 'blocked'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('parent_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('parent_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('parent_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
